---
- name: Install and configure Nginx
  hosts: webservers
  become: yes

  vars:
    my_name: "Varga Péter"

  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Enable and start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Set custom index.html
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Allow HTTP through firewall
      ansible.builtin.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
